name: Run commitlint on push
on: push
jobs:
  run-commitlin-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Commits"
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: "Run linting"
        run: |
          commits=${{ github.event.commits }}
          size=${#commits[@]}
          echo ${size}
          npx commitlint --from HEAD~1 --to HEAD --verbose
