name: "Run tests and lint on pr to master"

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-tests-and-lint-on-pr:
    uses: ./.github/workflows/test.yaml
  test-job:
    needs: run-tests-and-lint-on-pr
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.run-tests-and-lint-on-pr.outputs.result-link }}
