name: 'Create or hotfix release'

on:
  push:
    tags:
      - v[0-9]*
    branches:
      - 'releases/v[0-9]*'

jobs:
#  run-tests-on-release:
#    uses: ./.github/workflows/test.yaml
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Create release branch"
        if: ${{ github.ref_type == 'tag' }}
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: refs/heads/releases/${{ github.ref_name }}
  create-changelog:
    runs-on: ubuntu-latest
    needs: create-release-branch
    outputs:
      changelog: ${{ steps.step1.outputs.changelog }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        if: ${{ github.ref_type == 'tag' }}
        with:
          ref: releases/${{ github.ref_name }}
          fetch-depth: 0
      - name: "Checkout"
        uses: actions/checkout@v3
        if: ${{ github.ref_type == 'branch' }}
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
      - name: "Get diff commits"
        if: ${{ github.ref_type == 'tag' }}
        run: |
          changelog=$(git log --no-merges --pretty=format:"%s" $(git describe --abbrev=0 --tags ${{ github.ref_name }}^)...${{ github.ref_name }})
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "$changelog" >> "$GITHUB_OUTPUT"
      - name: "Get diff commits"
        if: ${{ github.ref_type == 'branch' }}
        run: |
          changelog=$(git log --no-merges --pretty=format:"%s" $(git describe --abbrev=0 --tags)^...HEAD)
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "$changelog" >> "$GITHUB_OUTPUT"
  create-issue:
    needs: create-changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Echo changelog"
        run: echo ${{ needs.create-changelog.outputs.changelog }}
