name: 'Create or hotfix release'

on:
  push:
    tags:
      - v[0-9]*
    branches:
      - 'releases/v[0-9]*'

jobs:
  run-tests-on-release:
    uses: ./.github/workflows/test.yaml
  create-release-branch:
    env:
      BRANCH_NAME: releases/${{ github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      branch-name: "$BRANCH_NAME"
    steps:
      - run: echo $BRANCH_NAME
      - name: "Create release branch"
        if: ${{ github.ref_type == 'tag' }}
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: refs/heads/"$BRANCH_NAME"
  create-changelog:
    env:
      BRANCH_NAME: ${{ needs.create-release-branch.outputs.branch-name }}
    runs-on: ubuntu-latest
    needs: create-release-branch
    outputs:
      changelog: ${{ steps.step1.outputs.changelog }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: $BRANCH_NAME
          fetch-depth: 0
      - name: "Get diff commits"
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "changelog=$(git log --no-merges --pretty=format:"%s" $(git describe --abbrev=0 --tags ${{ github.ref_name }}^)...${{ github.ref_name }})" >> "$GITHUB_OUTPUT"
      - name: "Get diff commits"
        if: ${{ github.ref_type == 'branch' }}
        run: |
          echo "changelog=$(git log --no-merges --pretty=format:"%s" $(git describe --abbrev=0 --tags)^...HEAD)" >> "$GITHUB_OUTPUT"
  create-issue:
    needs: create-changelog
    runs-on: ubuntu-latest
    steps:
      - name: "Echo changelog"
        run: echo ${{ needs.create-changelog.outputs.changelog }}
