name: 'Create or hotfix release'

on:
  push:
    tags:
      - v[0-9]*
    branches:
      - '/releases/v[0-9]*'

jobs:
  run-tests-on-release:
    uses: ./.github/workflows/test.yaml
  create-release-branch:
    env:
        BRANCH_NAME: releases/${{ github.ref_name }}
    runs-on: ubuntu-latest
    outputs:
      branch-name: $BRANCH_NAME
    steps:
      - name: "Create release branch"
        if: ${{ github.ref_type == 'tag' }}
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: refs/heads/$BRANCH_NAME
  create-changelog:
    env:
      BRANCH_NAME: ${{ needs.create-release-branch.outputs.branch-name }}
    runs-on: ubuntu-latest
    needs: create-release-branch
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: $BRANCH_NAME
          fetch-depth: 0
      - name: "Get diff commits"
        run: | 
          echo git log --no-merges --pretty=format:"%s" $(git describe --abbrev=0 --tags ${{ github.ref_name }}^)...${{ github.ref_name }}

