on:
  push:
    tags:
      - v[0-9]*
    branches:
      - '/releases/v[0-9]*'

jobs:
  run-tests-on-release:
    uses: ./.github/workflows/test.yaml
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: "Create release branch"
        if: ${{ github.ref_type == 'tag' }}
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: refs/heads/releases/${{ github.ref_name }}
