name: "Run tests and lint on pr to master"

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-linting-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm ci
      - name: "Run linting"
        run: npx eslint
  run-e2e-tests-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm ci
      - name: "Install Playwright Browsers"
        run: npx playwright install --with-deps
      - name: "Run Playwright tests"
        run: npx playwright test
      - name: "Save report"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  run-unit-tests-on-pr:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: "Install dependencies"
        run: npm ci
      - name: "Run unit tests"
        run: npm run test-ci
      - name: "Save report"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-report
          path: test-report.html
          retention-days: 30
